### PR TITLE
chore(deps): bump reth to v1.0.3

### PR DESCRIPTION
**Pull request by chirag-bgh**
## 📝 Summary

Update reth to latest v1.0.3 #47 

## 💡 Motivation and Context

---

## ✅ I have completed the following steps:

* [x] Run `make lint`
* [ ] Run `make test`
* [ ] Added tests (if applicable)

### CODE REVIEW

**Comment by chirag-bgh** [comment]
Waiting on #15 to be merged

**Comment by ferranbt** [comment]
Hey! Thank you for the contribution, amazing PR! I will review it first thing next week when I am back from Ethcc.

**Comment by ferranbt** [comment]
Can you rebase now that #15 is merged?

**Review by dvush — APPROVED** [review]
thanks! just rebased, did some tests and it looks good to go as is

**Pull request merged**
