### PR TITLE
feat: add parallel builder

### PR DESCRIPTION
**Pull request by bertmiller**
## 📝 Summary
This PR introduces a new building algorithm which parallelizes the process of building blocks. In particular,  it moves the largely sequential process of processing orders, resolving conflicts, and building blocks into modular and parallel process. Each of these components now runs in parallel, allowing for continuous intake of orderflow, flexible resolution of conflicts, and building blocks with the latest flow and best conflict resolution results. It is a significant architecture change.

See [run_parallel_builder](https://github.com/flashbots/rbuilder/blob/parallel-builder/crates/rbuilder/src/building/builders/parallel_builder/mod.rs#L180) for a good code entry point and the [readme.md](https://github.com/flashbots/rbuilder/blob/parallel-builder/crates/rbuilder/src/building/builders/parallel_builder/readme.md) for more architecture details.

Key Changes:
- Introduced a new parallel_builder module, replacing the merging_builder. This adds several components for orderflow intake, conflict identification, conflict resolution, and merging of resolved conflicts.
- Added a simulation cache to optimize repeated simulations of similar order sequences.
- Updated the builder configuration to use the new Parallel Builder instead of the Merging Builder.
- Implemented backtest functionality for the Parallel Builder.

## 💡 Motivation and Context

- Concurrency driven efficiency improvements: running significant processes in parallel is more efficient, and should lead to better blocks. Processes aren't sequential, so they aren't blocked on each other anymore.
- Reuses previous work: Instead of repeating conflict resolution, we are able to reuse old resolved conflict results.
- Better conflict management: We can prioritize "fast" conflict resolution tasks to get results for a conflict group to the building assembler fast, but then also queue "slow" tasks (like evolutionary algorithms) which might produce better results but are slower.

## Testing
Finally, I've added a range of tests to the new algorithm. I further have tested it extensively on a local node using mempool txs.

- ---

## ✅ I have completed the following steps:

* [✅ ] Run `make lint`
* [✅ ] Run `make test`
* [ ✅] Added tests (if applicable)

### CODE REVIEW

**Comment by bertmiller** [comment]
Not sure what is up with the lint. It passes locally.

**Review by dvush — APPROVED** [review]
I've looked at it before and it seems fine. Lint needs to fixed though. Are you using the same version of cargo/clippy/rust as we do in CI?

**Comment by bertmiller** [comment]
is `make lint` not the right lint?

**Comment by dvush** [comment]
try `rustup update` if you did not try before 

Liam changed this lint in his PR so I assume it  was added as part of the rust version update.

**Comment by bertmiller** [comment]
@dvush ok passing lint now, but I needed to add a Box<> to a variable. Does this commit look fine: https://github.com/flashbots/rbuilder/pull/219/commits/315fd3eab73a35a39ffad369cf3960e5b7b69c05

**Review by dvush — CHANGES_REQUESTED** [review]
I just rerun this version and it has a lot of unnecessary info logs.
Please, move all logs like that to TRACE instead on INFO. The rule of thumb is that if logs are on the order of O(number of bundles per slot) it should be trace. if its O(number of slots) it can be info.

```
2024-10-23T11:28:46.265176Z  INFO rbuilder::building::builders::parallel_builder::conflict_resolving_pool: Successfully ran conflict task task_type=AllPermutations group_id=236 profit="0.000166430785487103" order_count=1
2024-10-23T11:28:46.265283Z  INFO rbuilder::building::builders::parallel_builder::conflict_resolving_pool: Successfully ran conflict task task_type=Greedy group_id=237 profit="0.000091000317785005" order_count=1
2024-10-23T11:28:46.265309Z  INFO rbuilder::building::builders::parallel_builder::conflict_resolving_pool: Successfully ran conflict task task_type=AllPermutations group_id=237 profit="0.000091000317785005" order_count=1
2024-10-23T11:28:46.265393Z  INFO rbuilder::building::builders::parallel_builder::conflict_resolving_pool: Successfully ran conflict task task_type=Greedy group_id=238 profit="0.000000021000000000" order_count=1
2024-10-23T11:28:46.265419Z  INFO rbuilder::building::builders::parallel_builder::conflict_resolving_pool: Successfully ran conflict task task_type=AllPermutations group_id=238 profit="0.000000021000000000" order_count=1
```

**Comment by dvush** [comment]
Even after the fix It has too much logs. 

1. Backtest
```
2024-10-23T15:29:57.643736Z  INFO rbuilder::building::builders::parallel_builder: Initialization time: 304.854838ms
2024-10-23T15:29:57.643759Z  INFO rbuilder::building::builders::parallel_builder: Setup time: 218.923µs
2024-10-23T15:29:57.643761Z  INFO rbuilder::building::builders::parallel_builder: Group processing time: 11.240237149s
2024-10-23T15:29:57.643764Z  INFO rbuilder::building::builders::parallel_builder: Assembler creation time: 2.49539ms
2024-10-23T15:29:57.643770Z  INFO rbuilder::building::builders::parallel_builder: Best results collection time: 98.204µs
2024-10-23T15:29:57.643772Z  INFO rbuilder::building::builders::parallel_builder: Block building time: 63.054928ms
2024-10-23T15:29:57.643775Z  INFO rbuilder::building::builders::parallel_builder: Total time taken: 11.610960115s
```
we dont' do this for ordering builders and it breaks readability of the output when you run backtest across many blocks.

2. There are also logs like this when I run it live.

```
2024-10-23T15:37:04.249272Z DEBUG rbuilder::building::builders::parallel_builder::block_building_result_assembler: Parallel builder run id 42: Built new block with results version 52 and profit: "0.008066995911013489" in 3 ms
2024-10-23T15:37:04.252842Z DEBUG bid{bid_value="0.008058232921013489" best_bid_value="0.000000000000000000" true_bid_value="0.008058232921013489" block=21029230 hash=0x155fdd249daf97891b93516665bd7eab4bfd4db0585dd4e7d4a953ecf3ee04db gas=3329455 txs=52 bundles=0 buidler_name="merging" fill_time_ms=3 finalize_time_ms=3}: rbuilder::live_builder::block_output::relay_submit: Submitting bid
2024-10-23T15:37:04.264735Z DEBUG bid{bid_value="0.008066995911013489" best_bid_value="0.000000000000000000" true_bid_value="0.008066995911013489" block=21029230 hash=0x9ceda7d0b81a93884c10ed7f64ed9b9458d48dccf6d2043e1cb1a4215827e200 gas=3375576 txs=53 bundles=0 buidler_name="merging" fill_time_ms=3 finalize_time_ms=7}: rbuilder::live_builder::block_output::relay_submit: Submitting bid
2024-10-23T15:37:04.275655Z DEBUG rbuilder::building::builders::parallel_builder: Order intake: added new orders and processing groups new_orders_count=1 groups_count=52 time_taken_ms=0
2024-10-23T15:37:04.275836Z DEBUG rbuilder::building::builders::parallel_builder::block_building_result_assembler: Parallel builder run id 43: Attempting to build block with results version 53
2024-10-23T15:37:04.275849Z DEBUG rbuilder::building::builders::parallel_builder::results_aggregator: Updated best result for group group_id=51 old_profit="0.000000000000000000" new_profit="0.000452548658190464" sum_of_best_results="0.009050451177110145" number_of_orders=53 version=53 duration_ns=2044
2024-10-23T15:37:04.280003Z DEBUG rbuilder::building::builders::parallel_builder: Order intake: added new orders and processing groups new_orders_count=1 groups_count=53 time_taken_ms=0
2024-10-23T15:37:04.280050Z DEBUG rbuilder::building::builders::parallel_builder::block_building_result_assembler: Parallel builder run id 43: Built new block with results version 53 and profit: "0.008519544569203953" in 4 ms
2024-10-23T15:37:04.280100Z DEBUG rbuilder::building::builders::parallel_builder::block_building_result_assembler: Parallel builder run id 44: Attempting to build block with results version 54
2024-10-23T15:37:04.280112Z DEBUG rbuilder::building::builders::parallel_builder::results_aggregator: Updated best result for group group_id=52 old_profit="0.000000000000000000" new_profit="0.000001047096414000" sum_of_best_results="0.009051498273524145" number_of_orders=54 version=54 duration_ns=1072
2024-10-23T15:37:04.283819Z DEBUG rbuilder::building::builders::parallel_builder::block_building_result_assembler: Parallel builder run id 44: Built new block with results version 54 and profit: "0.008520591665617953" in 3 ms
2024-10-23T15:37:04.288750Z DEBUG bid{bid_value="0.008519544569203953" best_bid_value="0.000000000000000000" true_bid_value="0.008519544569203953" block=21029230 hash=0x819760f14dc70fb03b0af47ad0f303a0c68134c62bc6e97623024dcbd067651e gas=3416885 txs=54 bundles=0 buidler_name="mp-ordering" fill_time_ms=4 finalize_time_ms=4}: rbuilder::live_builder::block_output::relay_submit: Submitting bid
2024-10-23T15:37:04.294734Z DEBUG bid{bid_value="0.008520591665617953" best_bid_value="0.000000000000000000" true_bid_value="0.008520591665617953" block=21029230 hash=0x78b7c717784360ba6844dc2a16bc75b3f427bf2728b9904611902992844019d5 gas=3437885 txs=55 bundles=0 buidler_name="mp-ordering" fill_time_ms=4 finalize_time_ms=3}: rbuilder::live_builder::block_output::relay_submit: Submitting bid
2024-10-23T15:37:04.366897Z DEBUG rbuilder::building::builders::parallel_builder: Order intake: added new orders and processing groups new_orders_count=1 groups_count=54 time_taken_ms=0
2024-10-23T15:37:04.367042Z DEBUG rbuilder::building::builders::parallel_builder::block_building_result_assembler: Parallel builder run id 45: Attempting to build block with results version 55
2024-10-23T15:37:04.367054Z DEBUG rbuilder::building::builders::parallel_builder::results_aggregator: Updated best result for group group_id=53 old_profit="0.000000000000000000" new_profit="0.000065878179163340" sum_of_best_results="0.009117376452687485" number_of_orders=55 version=55 duration_ns=1854
2024-10-23T15:37:04.371615Z DEBUG rbuilder::building::builders::parallel_builder::block_building_result_assembler: Parallel builder run id 45: Built new block with results version 55 and profit: "0.008586469844781293" in 4 ms
```

All of this can theoretically be in debug if we would do that already but now they should be moved to trace because thats how we do it in the ordering builder right now and it will break readability of debug logs as they are done today. This would be equivalent to logging each ordering builder attempt in debug and we don't do that.

Right now in debug we log only for each bid that we submit but not each attempt of building a block and it works better because it only logs when bid is better than before so you can visually grasp the logs for the given slot. 

We can reconsider but that should be done separately with a whole logs overhaul so they are consistent.

**Comment by bertmiller** [comment]
@dvush thanks for the fast feedback, just moved all those logs to a trace

**Review by dvush — APPROVED** [review]
LGTM, the only thing needed is conflict resolution

We recently merged https://github.com/flashbots/rbuilder/pull/218 and it generated a lot of conflicts. They are not that bad as they seem, I recommend just looking at the diff for old merging builder and copying all the places where concrete provider is replaced with a trait.

**Comment by bertmiller** [comment]
Fixed and merged! Thanks @dvush :)

**Pull request merged**
